### PR TITLE
Project updates

### PR DESCRIPTION
**Pull request by sigrlami**
Hi, Chris. 
This PR provides a basic outline for different improvements we have for Slick built in collaboration with @mgajda. We want to create some momentum for the project and have a couple of websites already in production with `Slick` setup and our corrections. 

This PR includes:
- Addition of Serve.hs that include functionality for `Preview` mode that spins out small server for site observation
- Additional integration with our `shake-watch` project that will be released soon which provides continuous rebuilds on either `haskell` changes or `site` changes.
- Addition of Build.hs file that includes high-level goodies we created while working on multiple sites
- Updates example project
    - Additional keys
    - Additional Builder.hs file with everything related to builds and update to the main workflow where shakeRules and builder moved to separate functions for further reuse.
- Compacts README.md to concentrate on go-to production details (should be improved in later updates) and updates dependencies. 

I would like to get your feedback and establish the path to maintainership so I can push continuous updates and move this cool project further. In case you want to split into multiple smaller PRs we can also arrange that.

### CODE REVIEW

**Comment by sigrlami** [comment]
It's still work in progress and I'll finalize during next couple days and prepare for review.

**Comment by ChrisPenner** [comment]
Hi! The changes look interesting and good; I'd be interested in looking at getting them merged in. Is there a reason you've closed this issue?

I would prefer smaller PRs yes, I know it's a pain to do afterwards, but this is a large change and to do it "all or nothing" is very inconvenient for me.

Other thoughts:

* I notice you've changed the base repository in the `package.yaml`, are you requesting to move this project into your organization?
* This brings on a full webserver and websockets implementation as dependencies, I understand that `slick` already has a lot of dependencies (having `lens` and `pandoc` basically brings on everything under the sun) but for that reason I'm actually looking at reducing the number of dependencies I'm using if possible.  The webserver is really great and I'd still love to provide it somehow, to me it seems as though the auto-updating webserver should be implemented as a supplementary package/plugin which can enhance slick. Can we talk about what would be necessary for that to happen? We can look at exposing some hooks for plugins in Slick if it's necessary for the integration.
* This rewinds the version number of the project, I suspect that's just an oversight?

Looking forward to hearing from you.

**Comment by srid** [comment]
If we can take the websocket stuff out of the equation, the web server part can be simplified quite drastically. This is what I do in my own static site generator as well: https://github.com/srid/rib/blob/master/src/Rib/Server.hs

**Comment by sigrlami** [comment]
@ChrisPenner Hi, Chris. Thank you for feedback.

1) PR was closed due to the decision to simplify changes and get it more polished before you take a look, my mistake was rushing into making a PR. I anticipate to prepare a new PR in 1-2 days with more cleaner changes, stripped down just to 19 files. 

2) Change of version and base repository my mistake as initially, we wanted to keep the project as a fork but then decided it would be nice to contribute back.

3) Regarding webserver,  `Serve.hs` is a standalone module and can be easily moved to `slick-serve` or something similar.

I rushed to touch base as we have more upcoming features and I know it's difficult to work with big PR.

**Comment by sigrlami** [comment]
@srid Server side allows not only a local hosting with http server but also `live-reload` functionality that's why websockets required. We have `shake-watch` package almost ready for release that sends updates to websocket server and auto-reloads webpage with small js script

**Comment by mgajda** [comment]
@srid Note that live coding is major feature for power users.

**Comment by ChrisPenner** [comment]
Great, thanks for responding so quickly; that all sounds good to me 👍 

Looking forward to the new PR. Thanks for your time 😃

**Pull request closed without merging**
